In [15]:
import numpy as np
import pandas as pd
df = pd.read_csv('descriptors-alva-66-fix.csv')
ncol = df.shape[1]-1
x = df.iloc[:,0:ncol]
y = df['active']

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 1)

In [17]:
trainD = pd.concat([x_train, y_train], axis =1)
testD = pd.concat([x_test, y_test], axis =1)

In [18]:
F_sel = ['EE_B(s)', 'Mor16u', 'CATS2D_03_AL']
trainD = trainD[['EE_B(s)', 'Mor16u', 'CATS2D_03_AL','active']]
testD = testD[['EE_B(s)', 'Mor16u', 'CATS2D_03_AL','active']]

In [19]:
from pycaret.classification import *
cm = setup(data = trainD, target = 'active', train_size = 0.8, test_data = testD, silent=True,  numeric_features = F_sel,
             session_id=1, fold_strategy = 'stratifiedkfold', fold = 5, fold_shuffle = True, normalize = True)

In [20]:
compare_models()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
mlp = create_model('mlp')
tunedmlp = tune_model(mlp, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedmlp)

     EE_B(s)    Mor16u  CATS2D_03_AL  active  Label   Score
0   4.209669  0.114127     -0.418377       1      0  0.8708
1   1.617277  1.736262      1.730325       0      0  0.9955
2   4.363976 -1.174933     -0.418377       0      0  0.9790
3   1.725293 -0.700518      2.267500       0      0  0.9966
4  -0.234431 -0.823371     -0.418377       1      1  0.9478
5  -1.407179 -0.449445     -0.418377       0      1  0.9423
6   0.675992 -0.715129      0.118798       1      0  0.6133
7   1.679000 -0.998406      2.267500       1      0  0.9973
8   1.848740  0.412314      1.730325       0      0  0.9961
9  -0.172707 -0.151259     -0.418377       1      1  0.9979
10  1.432106  0.793993      1.730325       0      0  0.9961
11 -0.002968  2.383327     -0.418377       1      1  0.9919
12  0.058756  1.166726     -0.418377       0      1  0.9939
13  0.089618  1.190580      0.118798       1      1  0.9586

In [22]:
cat = create_model('catboost')
tunedcat = tune_model(cat, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedcat)

     EE_B(s)    Mor16u  CATS2D_03_AL  active  Label   Score
0   4.209669  0.114127     -0.418377       1      1  0.8181
1   1.617277  1.736262      1.730325       0      0  0.6300
2   4.363976 -1.174933     -0.418377       0      0  0.5891
3   1.725293 -0.700518      2.267500       0      0  0.8859
4  -0.234431 -0.823371     -0.418377       1      1  0.8685
5  -1.407179 -0.449445     -0.418377       0      1  0.8992
6   0.675992 -0.715129      0.118798       1      0  0.6199
7   1.679000 -0.998406      2.267500       1      0  0.9090
8   1.848740  0.412314      1.730325       0      0  0.8461
9  -0.172707 -0.151259     -0.418377       1      1  0.9349
10  1.432106  0.793993      1.730325       0      0  0.6359
11 -0.002968  2.383327     -0.418377       1      1  0.9059
12  0.058756  1.166726     -0.418377       0      1  0.8979
13  0.089618  1.190580      0.118798       1      1  0.8796

In [23]:
lgb = create_model('lightgbm')
tunedlgb = tune_model(lgb, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedlgb)

     EE_B(s)    Mor16u  CATS2D_03_AL  active  Label   Score
0   4.209669  0.114127     -0.418377       1      1  0.9348
1   1.617277  1.736262      1.730325       0      0  0.9376
2   4.363976 -1.174933     -0.418377       0      0  0.9277
3   1.725293 -0.700518      2.267500       0      0  0.9011
4  -0.234431 -0.823371     -0.418377       1      1  0.8091
5  -1.407179 -0.449445     -0.418377       0      1  0.9818
6   0.675992 -0.715129      0.118798       1      1  0.8903
7   1.679000 -0.998406      2.267500       1      0  0.9850
8   1.848740  0.412314      1.730325       0      0  0.9358
9  -0.172707 -0.151259     -0.418377       1      1  0.9958
10  1.432106  0.793993      1.730325       0      0  0.9358
11 -0.002968  2.383327     -0.418377       1      1  0.9604
12  0.058756  1.166726     -0.418377       0      1  0.9188
13  0.089618  1.190580      0.118798       1      1  0.9188

In [24]:
svm = create_model('rbfsvm')
tunedsvm = tune_model(svm, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedsvm)

     EE_B(s)    Mor16u  CATS2D_03_AL  active  Label   Score
0   4.209669  0.114127     -0.418377       1      0  0.5334
1   1.617277  1.736262      1.730325       0      0  0.8651
2   4.363976 -1.174933     -0.418377       0      0  0.5427
3   1.725293 -0.700518      2.267500       0      0  0.9180
4  -0.234431 -0.823371     -0.418377       1      1  0.7741
5  -1.407179 -0.449445     -0.418377       0      1  0.9856
6   0.675992 -0.715129      0.118798       1      0  0.5229
7   1.679000 -0.998406      2.267500       1      0  0.9193
8   1.848740  0.412314      1.730325       0      0  0.9341
9  -0.172707 -0.151259     -0.418377       1      1  0.9691
10  1.432106  0.793993      1.730325       0      0  0.9641
11 -0.002968  2.383327     -0.418377       1      1  0.8660
12  0.058756  1.166726     -0.418377       0      1  0.8261
13  0.089618  1.190580      0.118798       1      1  0.6659

In [25]:
xgb = create_model('xgboost')
tunedxgb = tune_model(xgb, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedxgb)

     EE_B(s)    Mor16u  CATS2D_03_AL  active  Label   Score
0   4.209669  0.114127     -0.418377       1      1  0.9707
1   1.617277  1.736262      1.730325       0      0  0.5788
2   4.363976 -1.174933     -0.418377       0      1  0.6556
3   1.725293 -0.700518      2.267500       0      0  0.8972
4  -0.234431 -0.823371     -0.418377       1      1  0.9763
5  -1.407179 -0.449445     -0.418377       0      1  0.9985
6   0.675992 -0.715129      0.118798       1      1  0.8164
7   1.679000 -0.998406      2.267500       1      0  0.9457
8   1.848740  0.412314      1.730325       0      0  0.5788
9  -0.172707 -0.151259     -0.418377       1      1  0.9990
10  1.432106  0.793993      1.730325       0      0  0.5788
11 -0.002968  2.383327     -0.418377       1      1  0.9975
12  0.058756  1.166726     -0.418377       0      1  0.9975
13  0.089618  1.190580      0.118798       1      1  0.9969

In [26]:
et = create_model('et')
tunedet = tune_model(et, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedet)

     EE_B(s)    Mor16u  CATS2D_03_AL  active  Label   Score
0   4.209669  0.114127     -0.418377       1      1  0.5015
1   1.617277  1.736262      1.730325       0      0  0.5265
2   4.363976 -1.174933     -0.418377       0      0  0.5083
3   1.725293 -0.700518      2.267500       0      0  0.5398
4  -0.234431 -0.823371     -0.418377       1      1  0.5227
5  -1.407179 -0.449445     -0.418377       0      1  0.5260
6   0.675992 -0.715129      0.118798       1      0  0.5083
7   1.679000 -0.998406      2.267500       1      0  0.5398
8   1.848740  0.412314      1.730325       0      0  0.5265
9  -0.172707 -0.151259     -0.418377       1      1  0.5293
10  1.432106  0.793993      1.730325       0      0  0.5265
11 -0.002968  2.383327     -0.418377       1      1  0.5288
12  0.058756  1.166726     -0.418377       0      1  0.5252
13  0.089618  1.190580      0.118798       1      1  0.5220

In [27]:
rf = create_model('rf')
tunedrf = tune_model(rf, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedrf)

     EE_B(s)    Mor16u  CATS2D_03_AL  active  Label   Score
0   4.209669  0.114127     -0.418377       1      1  0.5179
1   1.617277  1.736262      1.730325       0      0  0.8917
2   4.363976 -1.174933     -0.418377       0      0  0.5860
3   1.725293 -0.700518      2.267500       0      0  0.9440
4  -0.234431 -0.823371     -0.418377       1      1  0.7668
5  -1.407179 -0.449445     -0.418377       0      1  0.8562
6   0.675992 -0.715129      0.118798       1      0  0.5694
7   1.679000 -0.998406      2.267500       1      0  0.9440
8   1.848740  0.412314      1.730325       0      0  0.8917
9  -0.172707 -0.151259     -0.418377       1      1  0.9255
10  1.432106  0.793993      1.730325       0      0  0.8917
11 -0.002968  2.383327     -0.418377       1      1  0.8589
12  0.058756  1.166726     -0.418377       0      1  0.8548
13  0.089618  1.190580      0.118798       1      1  0.7842

In [28]:
gbc = create_model('gbc')
tunedgbc = tune_model(gbc, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedgbc)

     EE_B(s)    Mor16u  CATS2D_03_AL  active  Label   Score
0   4.209669  0.114127     -0.418377       1      1  0.8663
1   1.617277  1.736262      1.730325       0      0  0.9896
2   4.363976 -1.174933     -0.418377       0      0  0.9828
3   1.725293 -0.700518      2.267500       0      0  0.9983
4  -0.234431 -0.823371     -0.418377       1      1  0.8968
5  -1.407179 -0.449445     -0.418377       0      1  0.9982
6   0.675992 -0.715129      0.118798       1      0  0.7042
7   1.679000 -0.998406      2.267500       1      0  0.9999
8   1.848740  0.412314      1.730325       0      0  0.9586
9  -0.172707 -0.151259     -0.418377       1      1  0.9997
10  1.432106  0.793993      1.730325       0      0  0.9586
11 -0.002968  2.383327     -0.418377       1      1  0.9944
12  0.058756  1.166726     -0.418377       0      1  0.9986
13  0.089618  1.190580      0.118798       1      1  0.9985

In [29]:
gbc_tuned_model, gbc_tuner = tune_model(gbc, n_iter = 1,  search_library = 'optuna', optimize = 'AUC',return_tuner=True)
et_tuned_model, et_tuner = tune_model(et, n_iter = 1,  search_library = 'optuna', optimize = 'AUC',return_tuner=True)
lgb_tuned_model, lgb_tuner = tune_model(lgb, n_iter = 1,  search_library = 'optuna', optimize = 'AUC',return_tuner=True)
xgb_tuned_model, xgb_tuner = tune_model(xgb, n_iter = 1,  search_library = 'optuna', optimize = 'AUC',return_tuner=True)
svm_tuned_model, svm_tuner = tune_model(svm, n_iter = 1,  search_library = 'optuna', optimize = 'AUC',return_tuner=True)
mlp_tuned_model, mlp_tuner = tune_model(mlp, n_iter = 1,  search_library = 'optuna', optimize = 'AUC',return_tuner=True)

In [35]:
gbc_tuner.get_params(True)['param_distributions']

{'actual_estimator__n_estimators': IntUniformDistribution(high=300, low=10, step=1),
 'actual_estimator__learning_rate': LogUniformDistribution(high=0.5, low=1e-06),
 'actual_estimator__subsample': UniformDistribution(high=1.0, low=0.2),
 'actual_estimator__min_samples_split': IntUniformDistribution(high=10, low=2, step=1),
 'actual_estimator__min_samples_leaf': IntUniformDistribution(high=5, low=1, step=1),
 'actual_estimator__max_depth': IntUniformDistribution(high=11, low=1, step=1),
 'actual_estimator__min_impurity_decrease': LogUniformDistribution(high=0.5, low=1e-09),
 'actual_estimator__max_features': UniformDistribution(high=1.0, low=0.4)}

In [36]:
et_tuner.get_params(True)['param_distributions']

{'actual_estimator__n_estimators': IntUniformDistribution(high=300, low=10, step=1),
 'actual_estimator__max_depth': IntUniformDistribution(high=11, low=1, step=1),
 'actual_estimator__min_samples_split': IntUniformDistribution(high=10, low=2, step=1),
 'actual_estimator__min_samples_leaf': IntUniformDistribution(high=5, low=1, step=1),
 'actual_estimator__max_features': UniformDistribution(high=1.0, low=0.4),
 'actual_estimator__min_impurity_decrease': LogUniformDistribution(high=0.5, low=1e-09),
 'actual_estimator__criterion': CategoricalDistribution(choices=('gini', 'entropy')),
 'actual_estimator__bootstrap': CategoricalDistribution(choices=(True, False)),
 'actual_estimator__class_weight': CategoricalDistribution(choices=('balanced', 'balanced_subsample', {}))}

In [37]:
lgb_tuner.get_params(True)['param_distributions']

{'actual_estimator__num_leaves': IntUniformDistribution(high=256, low=2, step=1),
 'actual_estimator__learning_rate': LogUniformDistribution(high=0.5, low=1e-06),
 'actual_estimator__n_estimators': IntUniformDistribution(high=300, low=10, step=1),
 'actual_estimator__min_split_gain': UniformDistribution(high=1.0, low=0.0),
 'actual_estimator__reg_alpha': LogUniformDistribution(high=10.0, low=1e-10),
 'actual_estimator__reg_lambda': LogUniformDistribution(high=10.0, low=1e-10),
 'actual_estimator__feature_fraction': UniformDistribution(high=1.0, low=0.4),
 'actual_estimator__bagging_fraction': UniformDistribution(high=1.0, low=0.4),
 'actual_estimator__bagging_freq': IntUniformDistribution(high=7, low=0, step=1),
 'actual_estimator__min_child_samples': IntUniformDistribution(high=100, low=1, step=1)}

In [38]:
xgb_tuner.get_params(True)['param_distributions']

{'actual_estimator__learning_rate': LogUniformDistribution(high=0.5, low=1e-06),
 'actual_estimator__n_estimators': IntUniformDistribution(high=300, low=10, step=1),
 'actual_estimator__subsample': UniformDistribution(high=1.0, low=0.2),
 'actual_estimator__max_depth': IntUniformDistribution(high=11, low=1, step=1),
 'actual_estimator__colsample_bytree': UniformDistribution(high=1.0, low=0.5),
 'actual_estimator__min_child_weight': IntUniformDistribution(high=4, low=1, step=1),
 'actual_estimator__reg_alpha': LogUniformDistribution(high=10.0, low=1e-10),
 'actual_estimator__reg_lambda': LogUniformDistribution(high=10.0, low=1e-10),
 'actual_estimator__scale_pos_weight': UniformDistribution(high=50.0, low=1.0)}

In [39]:
svm_tuner.get_params(True)['param_distributions']

{'actual_estimator__C': UniformDistribution(high=50.0, low=0.0),
 'actual_estimator__class_weight': CategoricalDistribution(choices=('balanced', {}))}

In [41]:
mlp_tuner.get_params(True)['param_distributions']

{'actual_estimator__alpha': LogUniformDistribution(high=0.9999999999, low=1e-10),
 'actual_estimator__hidden_layer_size_0': IntUniformDistribution(high=100, low=50, step=1),
 'actual_estimator__hidden_layer_size_1': IntUniformDistribution(high=100, low=0, step=1),
 'actual_estimator__hidden_layer_size_2': IntUniformDistribution(high=100, low=0, step=1),
 'actual_estimator__learning_rate': CategoricalDistribution(choices=('constant', 'invscaling', 'adaptive')),
 'actual_estimator__activation': CategoricalDistribution(choices=('tanh', 'identity', 'logistic', 'relu'))}

In [42]:
svm_tuner

OptunaSearchCV(cv=StratifiedKFold(n_splits=5, random_state=1, shuffle=True),
               enable_pruning=False, error_score='raise',
               estimator=Pipeline(memory=None,
                                  steps=[('empty_step', 'passthrough'),
                                         ('actual_estimator',
                                          SVC(C=1.0, break_ties=False,
                                              cache_size=200, class_weight=None,
                                              coef0=0.0,
                                              decision_function_shape='ovr',
                                              degree=3, gamma='auto',
                                              kernel='rbf', max_iter=-1,
                                              p...
               param_distributions={'actual_estimator__C': UniformDistribution(high=50.0, low=0.0),
                                    'actual_estimator__class_weight': CategoricalDistribution(choices=('balanced', {}))},
               random_state=1, refit=False, return_train_score=False,
               scoring=make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr),
               study=<optuna.study.study.Study object at 0x7f054ee13910>,
               subsample=1.0, timeout=None, verbose=1)

In [44]:
mlp_tuner.get_params(True)

{'cv': StratifiedKFold(n_splits=5, random_state=1, shuffle=True),
 'enable_pruning': False,
 'error_score': 'raise',
 'estimator__memory': None,
 'estimator__steps': [('empty_step', 'passthrough'),
  ('actual_estimator',
   TunableMLPClassifier(activation='logistic', alpha=7.914564592305138e-07,
                        batch_size='auto', beta_1=0.9, beta_2=0.999,
                        early_stopping=False, epsilon=1e-08,
                        hidden_layer_size_0=57, hidden_layer_size_1=65,
                        hidden_layer_size_2=84, hidden_layer_sizes=[57, 65, 84],
                        learning_rate='constant', learning_rate_init=0.001,
                        max_fun=15000, max_iter=500, momentum=0.9,
                        n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
                        random_state=1, shuffle=True, solver='adam', tol=0.0001,
                        validation_fraction=0.1, verbose=False, warm_start=False))],
 'estimator__verbose': False,
 'estimator__empty_step': 'passthrough',
 'estimator__actual_estimator': TunableMLPClassifier(activation='logistic', alpha=7.914564592305138e-07,
                      batch_size='auto', beta_1=0.9, beta_2=0.999,
                      early_stopping=False, epsilon=1e-08,
                      hidden_layer_size_0=57, hidden_layer_size_1=65,
                      hidden_layer_size_2=84, hidden_layer_sizes=[57, 65, 84],
                      learning_rate='constant', learning_rate_init=0.001,
                      max_fun=15000, max_iter=500, momentum=0.9,
                      n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
                      random_state=1, shuffle=True, solver='adam', tol=0.0001,
                      validation_fraction=0.1, verbose=False, warm_start=False),
 'estimator__actual_estimator__activation': 'logistic',
 'estimator__actual_estimator__alpha': 7.914564592305138e-07,
 'estimator__actual_estimator__batch_size': 'auto',
 'estimator__actual_estimator__beta_1': 0.9,
 'estimator__actual_estimator__beta_2': 0.999,
 'estimator__actual_estimator__early_stopping': False,
 'estimator__actual_estimator__epsilon': 1e-08,
 'estimator__actual_estimator__hidden_layer_sizes': [57, 65, 84],
 'estimator__actual_estimator__learning_rate': 'constant',
 'estimator__actual_estimator__learning_rate_init': 0.001,
 'estimator__actual_estimator__max_fun': 15000,
 'estimator__actual_estimator__max_iter': 500,
 'estimator__actual_estimator__momentum': 0.9,
 'estimator__actual_estimator__n_iter_no_change': 10,
 'estimator__actual_estimator__nesterovs_momentum': True,
 'estimator__actual_estimator__power_t': 0.5,
 'estimator__actual_estimator__random_state': 1,
 'estimator__actual_estimator__shuffle': True,
 'estimator__actual_estimator__solver': 'adam',
 'estimator__actual_estimator__tol': 0.0001,
 'estimator__actual_estimator__validation_fraction': 0.1,
 'estimator__actual_estimator__verbose': False,
 'estimator__actual_estimator__warm_start': False,
 'estimator__actual_estimator__hidden_layer_size_0': 57,
 'estimator__actual_estimator__hidden_layer_size_1': 65,
 'estimator__actual_estimator__hidden_layer_size_2': 84,
 'estimator': Pipeline(memory=None,
          steps=[('empty_step', 'passthrough'),
                 ('actual_estimator',
                  TunableMLPClassifier(activation='logistic',
                                       alpha=7.914564592305138e-07,
                                       batch_size='auto', beta_1=0.9,
                                       beta_2=0.999, early_stopping=False,
                                       epsilon=1e-08, hidden_layer_size_0=57,
                                       hidden_layer_size_1=65,
                                       hidden_layer_size_2=84,
                                       hidden_layer_sizes=[57, 65, 84],
                                       learning_rate='constant',
                                       learning_rate_init=0.001, max_fun=15000,
                                       max_iter=500, momentum=0.9,
                                       n_iter_no_change=10,
                                       nesterovs_momentum=True, power_t=0.5,
                                       random_state=1, shuffle=True,
                                       solver='adam', tol=0.0001,
                                       validation_fraction=0.1, verbose=False,
                                       warm_start=False))],
          verbose=False),
 'max_iter': 10,
 'n_jobs': -1,
 'n_trials': 1,
 'param_distributions': {'actual_estimator__alpha': LogUniformDistribution(high=0.9999999999, low=1e-10),
  'actual_estimator__hidden_layer_size_0': IntUniformDistribution(high=100, low=50, step=1),
  'actual_estimator__hidden_layer_size_1': IntUniformDistribution(high=100, low=0, step=1),
  'actual_estimator__hidden_layer_size_2': IntUniformDistribution(high=100, low=0, step=1),
  'actual_estimator__learning_rate': CategoricalDistribution(choices=('constant', 'invscaling', 'adaptive')),
  'actual_estimator__activation': CategoricalDistribution(choices=('tanh', 'identity', 'logistic', 'relu'))},
 'random_state': 1,
 'refit': False,
 'return_train_score': False,
 'scoring': make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr),
 'study': <optuna.study.study.Study at 0x7f0553f679a0>,
 'subsample': 1.0,
 'timeout': None,
 'verbose': 1}

In [45]:
gbc_tuned_model, gbc_tuner = tune_model(gbc, n_iter = 1,  search_library = 'scikit-optimize', optimize = 'AUC',return_tuner=True)

In [46]:
gbc_tuner.get_params(True)

{'cv': StratifiedKFold(n_splits=5, random_state=1, shuffle=True),
 'error_score': 'raise',
 'estimator__memory': None,
 'estimator__steps': [('empty_step', 'passthrough'),
  ('actual_estimator',
   GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                              learning_rate=0.1, loss='deviance', max_depth=3,
                              max_features=None, max_leaf_nodes=None,
                              min_impurity_decrease=0.0, min_impurity_split=None,
                              min_samples_leaf=1, min_samples_split=2,
                              min_weight_fraction_leaf=0.0, n_estimators=100,
                              n_iter_no_change=None, presort='deprecated',
                              random_state=1, subsample=1.0, tol=0.0001,
                              validation_fraction=0.1, verbose=0,
                              warm_start=False))],
 'estimator__verbose': False,
 'estimator__empty_step': 'passthrough',
 'estimator__actual_estimator': GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                            learning_rate=0.1, loss='deviance', max_depth=3,
                            max_features=None, max_leaf_nodes=None,
                            min_impurity_decrease=0.0, min_impurity_split=None,
                            min_samples_leaf=1, min_samples_split=2,
                            min_weight_fraction_leaf=0.0, n_estimators=100,
                            n_iter_no_change=None, presort='deprecated',
                            random_state=1, subsample=1.0, tol=0.0001,
                            validation_fraction=0.1, verbose=0,
                            warm_start=False),
 'estimator__actual_estimator__ccp_alpha': 0.0,
 'estimator__actual_estimator__criterion': 'friedman_mse',
 'estimator__actual_estimator__init': None,
 'estimator__actual_estimator__learning_rate': 0.1,
 'estimator__actual_estimator__loss': 'deviance',
 'estimator__actual_estimator__max_depth': 3,
 'estimator__actual_estimator__max_features': None,
 'estimator__actual_estimator__max_leaf_nodes': None,
 'estimator__actual_estimator__min_impurity_decrease': 0.0,
 'estimator__actual_estimator__min_impurity_split': None,
 'estimator__actual_estimator__min_samples_leaf': 1,
 'estimator__actual_estimator__min_samples_split': 2,
 'estimator__actual_estimator__min_weight_fraction_leaf': 0.0,
 'estimator__actual_estimator__n_estimators': 100,
 'estimator__actual_estimator__n_iter_no_change': None,
 'estimator__actual_estimator__presort': 'deprecated',
 'estimator__actual_estimator__random_state': 1,
 'estimator__actual_estimator__subsample': 1.0,
 'estimator__actual_estimator__tol': 0.0001,
 'estimator__actual_estimator__validation_fraction': 0.1,
 'estimator__actual_estimator__verbose': 0,
 'estimator__actual_estimator__warm_start': False,
 'estimator': Pipeline(memory=None,
          steps=[('empty_step', 'passthrough'),
                 ('actual_estimator',
                  GradientBoostingClassifier(ccp_alpha=0.0,
                                             criterion='friedman_mse', init=None,
                                             learning_rate=0.1, loss='deviance',
                                             max_depth=3, max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=100,
                                             n_iter_no_change=None,
                                             presort='deprecated',
                                             random_state=1, subsample=1.0,
                                             tol=0.0001, validation_fraction=0.1,
                                             verbose=0, warm_start=False))],
          verbose=False),
 'fit_params': None,
 'iid': 'deprecated',
 'n_iter': 1,
 'n_jobs': -1,
 'n_points': 1,
 'optimizer_kwargs': None,
 'pre_dispatch': '2*n_jobs',
 'random_state': 1,
 'refit': False,
 'return_train_score': False,
 'scoring': make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr),
 'search_spaces': {'actual_estimator__n_estimators': Integer(low=10, high=300, prior='uniform', transform='normalize'),
  'actual_estimator__learning_rate': Real(low=1e-06, high=0.5, prior='log-uniform', transform='normalize'),
  'actual_estimator__subsample': Real(low=0.2, high=1, prior='uniform', transform='normalize'),
  'actual_estimator__min_samples_split': Integer(low=2, high=10, prior='uniform', transform='normalize'),
  'actual_estimator__min_samples_leaf': Integer(low=1, high=5, prior='uniform', transform='normalize'),
  'actual_estimator__max_depth': Integer(low=1, high=11, prior='uniform', transform='normalize'),
  'actual_estimator__min_impurity_decrease': Real(low=1e-09, high=0.5, prior='log-uniform', transform='normalize'),
  'actual_estimator__max_features': Real(low=0.4, high=1, prior='uniform', transform='normalize')},
 'verbose': 1}

/home/admin/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:846: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
/home/admin/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:846: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
/home/admin/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:846: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)

In [47]:
cat_tuned_model,cat_tuner = tune_model(cat, n_iter = 1,  search_library = 'optuna', optimize = 'AUC',return_tuner=True)

In [49]:
cat_tuner.get_params(True)['param_distributions']

{'actual_estimator__eta': LogUniformDistribution(high=0.5, low=1e-06),
 'actual_estimator__depth': IntUniformDistribution(high=11, low=1, step=1),
 'actual_estimator__n_estimators': IntUniformDistribution(high=300, low=10, step=1),
 'actual_estimator__random_strength': UniformDistribution(high=0.8, low=0.0),
 'actual_estimator__l2_leaf_reg': IntLogUniformDistribution(high=200, low=1, step=1)}