In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('descriptors-alva-66-fix.csv')
ncol = df.shape[1]-1
x = df.iloc[:,0:ncol]
y = df['active']

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 7)

In [3]:
trainD = pd.concat([x_train, y_train], axis =1)
testD = pd.concat([x_test, y_test], axis =1)

In [4]:
F_sel = ['O%', 'ZM1Kup', 'EE_B(s)']
trainD = trainD[['O%', 'ZM1Kup', 'EE_B(s)','active']]
testD = testD[['O%', 'ZM1Kup', 'EE_B(s)','active']]

In [5]:
from pycaret.classification import *
cm = setup(data = trainD, target = 'active', train_size = 0.8, test_data = testD, silent=True,  numeric_features = F_sel,
             session_id=7, fold_strategy = 'stratifiedkfold', fold = 5, fold_shuffle = True, normalize = True,n_jobs = 10)

In [6]:
compare_models()

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=7, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [7]:
mlp = create_model('mlp')
tunedmlp = tune_model(mlp, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedmlp)

          O%    ZM1Kup   EE_B(s)  active  Label   Score
0   0.994381  0.258853  1.056898       0      0  0.7562
1   0.670951  0.399002  1.212656       0      0  0.5885
2  -0.477951 -0.374862 -0.261056       1      1  0.9947
3   0.284765  0.484309 -1.159662       1      0  0.7398
4  -0.074870  0.057770 -0.081335       1      0  0.6209
5   0.444067 -0.265181  0.098386       0      0  0.5092
6   0.970244  1.922356  1.308508       0      0  0.9827
7  -0.586565 -1.142633 -1.087773       1      1  0.9918
8  -0.774831  0.344161 -0.057373       1      0  0.8098
9   0.207528  0.728046  0.985010       0      0  0.8452
10  1.163337  0.295414  1.068880       0      0  0.7996
11  2.128800 -0.521104  0.385940       1      0  0.9393
12  1.597795 -0.496731  0.397921       1      0  0.8659
13  0.897834 -0.326115  0.086405       0      0  0.6516

In [8]:
cat = create_model('catboost')
tunedcat = tune_model(cat, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedcat)

          O%    ZM1Kup   EE_B(s)  active  Label   Score
0   0.994381  0.258853  1.056898       0      0  0.5705
1   0.670951  0.399002  1.212656       0      0  0.6821
2  -0.477951 -0.374862 -0.261056       1      1  0.8555
3   0.284765  0.484309 -1.159662       1      1  0.5533
4  -0.074870  0.057770 -0.081335       1      1  0.8126
5   0.444067 -0.265181  0.098386       0      1  0.8212
6   0.970244  1.922356  1.308508       0      0  0.7207
7  -0.586565 -1.142633 -1.087773       1      1  0.5930
8  -0.774831  0.344161 -0.057373       1      0  0.7158
9   0.207528  0.728046  0.985010       0      1  0.5428
10  1.163337  0.295414  1.068880       0      0  0.5684
11  2.128800 -0.521104  0.385940       1      0  0.6946
12  1.597795 -0.496731  0.397921       1      0  0.7049
13  0.897834 -0.326115  0.086405       0      0  0.7278

In [12]:
lgb = create_model('lightgbm')
tunedlgb = tune_model(lgb, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedlgb)

          O%    ZM1Kup   EE_B(s)  active  Label   Score
0   0.994381  0.258853  1.056898       0      1  0.6345
1   0.670951  0.399002  1.212656       0      1  0.6345
2  -0.477951 -0.374862 -0.261056       1      1  0.6347
3   0.284765  0.484309 -1.159662       1      1  0.6346
4  -0.074870  0.057770 -0.081335       1      1  0.6346
5   0.444067 -0.265181  0.098386       0      1  0.6346
6   0.970244  1.922356  1.308508       0      1  0.6345
7  -0.586565 -1.142633 -1.087773       1      1  0.6347
8  -0.774831  0.344161 -0.057373       1      1  0.6345
9   0.207528  0.728046  0.985010       0      1  0.6345
10  1.163337  0.295414  1.068880       0      1  0.6345
11  2.128800 -0.521104  0.385940       1      1  0.6346
12  1.597795 -0.496731  0.397921       1      1  0.6346
13  0.897834 -0.326115  0.086405       0      1  0.6346

In [10]:
svm = create_model('rbfsvm')
tunedsvm = tune_model(svm, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedsvm)

          O%    ZM1Kup   EE_B(s)  active  Label   Score
0   0.994381  0.258853  1.056898       0      0  0.5383
1   0.670951  0.399002  1.212656       0      1  0.4774
2  -0.477951 -0.374862 -0.261056       1      1  0.9732
3   0.284765  0.484309 -1.159662       1      0  0.7323
4  -0.074870  0.057770 -0.081335       1      1  0.5593
5   0.444067 -0.265181  0.098386       0      1  0.6285
6   0.970244  1.922356  1.308508       0      0  0.8531
7  -0.586565 -1.142633 -1.087773       1      1  0.9924
8  -0.774831  0.344161 -0.057373       1      0  0.8377
9   0.207528  0.728046  0.985010       0      0  0.9410
10  1.163337  0.295414  1.068880       0      0  0.5520
11  2.128800 -0.521104  0.385940       1      0  0.9862
12  1.597795 -0.496731  0.397921       1      0  0.9637
13  0.897834 -0.326115  0.086405       0      0  0.7190

In [11]:
xgb = create_model('xgboost')
tunedxgb = tune_model(xgb, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedxgb)

          O%    ZM1Kup   EE_B(s)  active  Label   Score
0   0.994381  0.258853  1.056898       0      1  0.5655
1   0.670951  0.399002  1.212656       0      1  0.5680
2  -0.477951 -0.374862 -0.261056       1      1  0.5919
3   0.284765  0.484309 -1.159662       1      1  0.5830
4  -0.074870  0.057770 -0.081335       1      1  0.5880
5   0.444067 -0.265181  0.098386       0      1  0.5867
6   0.970244  1.922356  1.308508       0      1  0.5707
7  -0.586565 -1.142633 -1.087773       1      1  0.5911
8  -0.774831  0.344161 -0.057373       1      1  0.5786
9   0.207528  0.728046  0.985010       0      1  0.5702
10  1.163337  0.295414  1.068880       0      1  0.5650
11  2.128800 -0.521104  0.385940       1      1  0.5711
12  1.597795 -0.496731  0.397921       1      1  0.5711
13  0.897834 -0.326115  0.086405       0      1  0.5770

In [12]:
et = create_model('et')
tunedet = tune_model(et, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedet)

          O%    ZM1Kup   EE_B(s)  active  Label   Score
0   0.994381  0.258853  1.056898       0      0  0.6085
1   0.670951  0.399002  1.212656       0      0  0.5894
2  -0.477951 -0.374862 -0.261056       1      1  0.5979
3   0.284765  0.484309 -1.159662       1      1  0.5394
4  -0.074870  0.057770 -0.081335       1      1  0.5592
5   0.444067 -0.265181  0.098386       0      1  0.5147
6   0.970244  1.922356  1.308508       0      0  0.6083
7  -0.586565 -1.142633 -1.087773       1      1  0.6018
8  -0.774831  0.344161 -0.057373       1      1  0.5502
9   0.207528  0.728046  0.985010       0      0  0.5408
10  1.163337  0.295414  1.068880       0      0  0.6170
11  2.128800 -0.521104  0.385940       1      0  0.5921
12  1.597795 -0.496731  0.397921       1      0  0.5858
13  0.897834 -0.326115  0.086405       0      0  0.5299

In [13]:
rf = create_model('rf')
tunedrf = tune_model(rf, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedrf)

          O%    ZM1Kup   EE_B(s)  active  Label   Score
0   0.994381  0.258853  1.056898       0      0  0.8988
1   0.670951  0.399002  1.212656       0      0  0.8912
2  -0.477951 -0.374862 -0.261056       1      1  0.9641
3   0.284765  0.484309 -1.159662       1      1  0.5299
4  -0.074870  0.057770 -0.081335       1      1  0.5819
5   0.444067 -0.265181  0.098386       0      0  0.5254
6   0.970244  1.922356  1.308508       0      0  0.8912
7  -0.586565 -1.142633 -1.087773       1      1  0.8309
8  -0.774831  0.344161 -0.057373       1      0  0.6969
9   0.207528  0.728046  0.985010       0      0  0.6877
10  1.163337  0.295414  1.068880       0      0  0.9009
11  2.128800 -0.521104  0.385940       1      0  0.7605
12  1.597795 -0.496731  0.397921       1      0  0.7605
13  0.897834 -0.326115  0.086405       0      0  0.7809

In [14]:
gbc = create_model('gbc')
tunedgbc = tune_model(gbc, n_iter = 1000,  search_library = 'optuna', optimize = 'AUC')
predict_model(tunedgbc)

          O%    ZM1Kup   EE_B(s)  active  Label   Score
0   0.994381  0.258853  1.056898       0      0  0.6666
1   0.670951  0.399002  1.212656       0      0  0.6816
2  -0.477951 -0.374862 -0.261056       1      1  0.8546
3   0.284765  0.484309 -1.159662       1      1  0.5534
4  -0.074870  0.057770 -0.081335       1      1  0.7407
5   0.444067 -0.265181  0.098386       0      1  0.6918
6   0.970244  1.922356  1.308508       0      0  0.6634
7  -0.586565 -1.142633 -1.087773       1      1  0.7524
8  -0.774831  0.344161 -0.057373       1      0  0.5524
9   0.207528  0.728046  0.985010       0      0  0.6071
10  1.163337  0.295414  1.068880       0      0  0.6705
11  2.128800 -0.521104  0.385940       1      0  0.6125
12  1.597795 -0.496731  0.397921       1      0  0.6177
13  0.897834 -0.326115  0.086405       0      0  0.5530